export const API_URLS = {
  SIGNIN: "api/signin",
  COMMUNICATIONTYPE: "communication/type",
  CALLSTAFF: "call/staff",
  CALLSTATUS: "call/status",
  COMMUNICATION: "communication",
  CARECOORDINATORDETAILS: "staff",
  PATIENTDETAILS: "patient",
  COUNT:"communication/count",
  CONVERSATIONPATIENT:"patient",
  CONVERSATIONSTAFF:"staff",
  CONVERSATIONGLOBALCODE:"globalCode",
  FILE:"file",
  TIMEZONE:"timezone",
  CALL:"call",
  CONFERENCE:"appointment/conference",
  NEW:"appointment/new",
};
